[toolchain]
anchor_version = "1.2.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
manifest = "4DCvHBveVC31TztNNzJp65GeHxNNdPFVxH4vgwDwa7S9"

[programs.localnet]
manifest = "4DCvHBveVC31TztNNzJp65GeHxNNdPFVxH4vgwDwa7S9"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/manifest-dev.json"

[scripts]
test = "cargo test -p manifest-tests"

[hooks]
