// Copies the Anchor build output (target/idl, target/types) into the SDK so the app and
// scripts can build without the Rust toolchain. Run after `anchor build`:
//   pnpm idl:sync
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const outDir = resolve(root, "packages/sdk/src/idl");
mkdirSync(outDir, { recursive: true });

const idl = JSON.parse(readFileSync(resolve(root, "target/idl/manifest.json"), "utf8"));
const types = readFileSync(resolve(root, "target/types/manifest.ts"), "utf8");

writeFileSync(
  resolve(outDir, "idl.ts"),
  `// Generated by scripts/sync-idl.mjs from target/idl/manifest.json. Do not edit.\n` +
    `export const IDL = ${JSON.stringify(idl, null, 2)} as const;\n`,
);
writeFileSync(
  resolve(outDir, "manifest.ts"),
  `// Generated by scripts/sync-idl.mjs from target/types/manifest.ts. Do not edit.\n${types}`,
);
console.log(`IDL synced: program ${idl.address}, ${idl.instructions.length} instructions`);
